// Generated by https://quicktype.io

export interface Tweet {
    created_at:                    string;
    id:                            number;
    id_str:                        string;
    text:                          string;
    truncated:                     boolean;
    entities:                      TweetEntities;
    source:                        string;
    in_reply_to_status_id:         null;
    in_reply_to_status_id_str:     null;
    in_reply_to_user_id:           null;
    in_reply_to_user_id_str:       null;
    in_reply_to_screen_name:       null;
    user:                          User;
    geo:                           null;
    coordinates:                   null;
    place:                         null;
    contributors:                  null;
    is_quote_status:               boolean;
    retweet_count:                 number;
    favorite_count:                number;
    favorited:                     boolean;
    retweeted:                     boolean;
    possibly_sensitive:            boolean;
    possibly_sensitive_appealable: boolean;
    lang:                          string;
}

export interface TweetEntities {
    hashtags:      any[];
    symbols:       any[];
    user_mentions: any[];
    urls:          URL[];
}

export interface URL {
    url:          string;
    expanded_url: string;
    display_url:  string;
    indices:      number[];
}

export interface User {
    id:                                 number;
    id_str:                             string;
    name:                               string;
    screen_name:                        string;
    location:                           string;
    description:                        string;
    url:                                string;
    entities:                           UserEntities;
    protected:                          boolean;
    followers_count:                    number;
    friends_count:                      number;
    listed_count:                       number;
    created_at:                         string;
    favourites_count:                   number;
    utc_offset:                         null;
    time_zone:                          null;
    geo_enabled:                        null;
    verified:                           boolean;
    statuses_count:                     number;
    lang:                               string;
    contributors_enabled:               null;
    is_translator:                      null;
    is_translation_enabled:             null;
    profile_background_color:           string;
    profile_background_image_url:       string;
    profile_background_image_url_https: string;
    profile_background_tile:            string;
    profile_image_url:                  string;
    profile_image_url_https:            string;
    profile_banner_url:                 string;
    profile_link_color:                 string;
    profile_sidebar_border_color:       string;
    profile_sidebar_fill_color:         string;
    profile_text_color:                 string;
    profile_use_background_image:       null;
    has_extended_profile:               null;
    default_profile:                    boolean;
    default_profile_image:              boolean;
    following:                          null;
    follow_request_sent:                null;
    notifications:                      null;
    translator_type:                    string;
}

export interface UserEntities {
    url:         Description;
    description: Description;
}

export interface Description {
    urls: URL[];
}
